### PR TITLE
Add fail-on functions, tests, and constants for reporting module

### PR DESCRIPTION
**Pull request by victoria-miltcheva**
## Related issue

Supports internal issue 623 in Team-backlog

## Description of changes

This is a sub-PR of https://github.com/IBM/detect-secrets/pull/46 (I'm breaking down the reporting PR for easier readability for reviewers).

- Added `get_secrets_list_from_file` to `audit.py`. This makes it simpler to extract a list of secrets from a baseline file. To be used by fail on functions to get secrets list, as well as for getting secrets information for the report console output.
- Added `conditions.py` to a reporting directory under `detect-secrets/core`. The functions within this file correspond to the report `fail-on-xx` CLI arguments.
- Added a `constants.py` file which contains exit report exit code and secret type enums ~as well as custom types~.
- Added a `conditions_test.py` file which contains various tests for the `fail-on` functionality.
- Added a `baseline.py` to the `testing` directory since I noticed this baseline dictionary object is reused throughout our testing files.

### CODE REVIEW

**Comment by victoria-miltcheva** [comment]
`TypedDict` wasn't added until Python 3.8 🤦 , so we may not be able to annotate with custom types 😞 .
https://github.com/python/typeshed/issues/3500#issuecomment-558205265

**Comment by victoria-miltcheva** [comment]
The build is now failing due to insufficient test coverage:

```
py38 run-test: commands[3] | coverage report --show-missing '--include=tests/*' --fail-under 100

Name                                   Stmts   Miss Branch BrPart  Cover   Missing

----------------------------------------------------------------------------------

tests/core/report/conditions_test.py     113      3     14      1    97%   20-21, 28

----------------------------------------------------------------------------------

TOTAL                                   2144      3    280      1    99%

35 files skipped due to complete coverage.

Coverage failure: total of 99 is less than fail-under=100

ERROR: InvocationError for command /home/travis/build/IBM/detect-secrets/.tox/py38/bin/coverage report --show-missing '--include=tests/*' --fail-under 100 (exited with code 2)

___________________________________ summary ____________________________________

ERROR:   py38: commands failed

Makefile:16: recipe for target 'test' failed

make: *** [test] Error 1

The command "make test" exited with 2.
cache.2

store build cache

Done. Your build exited with 1.
```

So I can take one of two approaches:

- 1: Continue creating separate PRs for the reporting feature
   - Pros: smaller, more digestible PRs for reviewers
   - Cons build will fail until all the PRs have been merged (future PRs will add more test coverage)
- 2: Have a mega-PR with all changes (example: https://github.com/IBM/detect-secrets/pull/46)
   - Pros: test coverage check will pass
   - Cons: reviewers may miss things, more difficult to review

^ My preference is option 1, we just accept that the test coverage check will fail until all PRs are finished being merged.

**Comment by shamilpatel25** [comment]
Have u already rebased this with the staging branch? I know you merged a few other prs before this last one

**Comment by victoria-miltcheva** [comment]
> Have u already rebased this with the staging branch? I know you merged a few other prs before this last one

All done!

**Review by tefiggins — APPROVED** [review]
LGTM

**Review by shamilpatel25 — APPROVED** [review]

**Pull request merged**
