### PR TITLE
Add output functions and tests for reporting module

### PR DESCRIPTION
**Pull request by victoria-miltcheva**
## Related issue

Supports internal issue 623 in Team-backlog

## Description of changes

This is a sub-PR of https://github.com/IBM/detect-secrets/pull/46 (I'm breaking down the reporting PR for easier readability for reviewers).

- `output.py`: contains functions for table, json, stats, and instructions output.
- `output_test.py`: contains tests for output functions
- `requirements-dev`: added `tabulate` package
- `setup.py`: added `tabulate` pip package as a required install (meaning this will be installed when the detect-secrets pip package is installed since the table generation is dependent on it)

### CODE REVIEW

**Comment by victoria-miltcheva** [comment]
## Case: no secrets failed conditions

```
~ detect-secrets audit --report .secrets.baseline 

35 potential secrets in .secrets.baseline were reviewed. All checks have passed.

        - No unaudited secrets were found

        - No live secrets were found

        - No secrets that were audited as real were found
```

**Comment by victoria-miltcheva** [comment]
I just noticed something:
```
$ detect-secrets audit --report --omit-instructions --fail-on-live .secrets.baseline

35 potential secrets in .secrets.baseline were reviewed. Found 1 live secret, 0 unaudited secrets, and 0 secrets that were audited as real.

Failed Condition    Secret Type     Filename                Line
------------------  --------------  --------------------  ------
Live                Secret Keyword  config/production.ts      16

Failed conditions:

        - Live secrets were found

```
^ the stats text in this part shouldn't include the other condition checks since we're only telling DS to check for live secrets. I will fix this tomorrow for the other fail-on cases as well!

**Comment by victoria-miltcheva** [comment]
Build fails due to test coverage; this check will pass once all my reporting sub-PRs have been merged.

**Comment by victoria-miltcheva** [comment]
Ready for review!

**Review by shamilpatel25 — APPROVED** [review]

**Pull request merged**
